name: wait-for-docker-image-action
description: Action to wait until Docker image is available

inputs:
  tags:
    description: Docker tags (multi-line string)
    required: true
  expected-revision:
    description: expected Git revisions (multi-line string)
    required: true
    default: |
      ${{ github.sha }}
      ${{ github.event.pull_request.head.sha }}
  timeout-seconds:
    description: timeout in seconds
    required: true
    default: '600'
  polling-seconds:
    description: polling interval in seconds
    required: true
    default: '5'

runs:
  using: 'node16'
  main: 'dist/index.js'
