name: e2e

on:
  pull_request:
    paths:
      - src/**
      - tests/fixtures/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/fixtures/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/fixture
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/fixture
      - uses: ./
        with:
          tags: ${{ steps.metadata.outputs.tags }}
