name: e2e

on:
  pull_request:
    paths:
      - src/**
      - tests/fixtures/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/fixtures/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/fixture
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/fixture
      - uses: ./
        with:
          tags: ${{ steps.metadata.outputs.tags }}
